[book]
authors = ["ellttBen"]
language = "en"
multilingual = false
src = "src"
title = "The Bonfida Development Guide"

[build]
build-dir = "docs"

[output.html]
cname = "utils.bonfida.org"
git-repository-url = "https://github.com/Bonfida/bonfida-dev-guide/"